use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'NEUGank' do
    pod 'Masonry'
    pod 'AFNetworking', '~> 3.0'
    pod 'YYModel'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'UMengSocialCOM', '~> 5.2.1'
    pod 'AVOSCloud'
end



